**Array Basics**

1.Attributes of an array
Introduce attributes that describe the array .
Attributes: .shape,.ndim,.size,.dtype

In [2]:
import numpy as np
arr = np.array([[1,2,3,],[4,5,6]])

print("which dimensional of array :- ",arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

which dimensional of array :-  (2, 3)
2
6
int64


Indexing and Slicing
Now we have indexing and slicing aswell and for that we are going to see 1d indexing lets start with 1 d indexing and it is similar to list.

In [3]:
arr = np.array([1,2,3,4,5])
print(arr[0])
print(arr[1])

1
2


Now lets see 2D indexing

In [4]:
arr = np.array(([2,3,5],[7,8,9],[1,5,8]))
arr
print(arr[0])

[2 3 5]


Now we can also do the slicing lets see the slicing in 1D

In [5]:
a = np.array([1,2,3,4,5,6,7])
a[:3]

array([1, 2, 3])

lets see the slicing in 2D

In [6]:
arr = np.array([[1,2,3],[6,4,5],[6,7,8],[3,9,10]])
print(arr)
arr[0:2,0:2]

[[ 1  2  3]
 [ 6  4  5]
 [ 6  7  8]
 [ 3  9 10]]


array([[1, 2],
       [6, 4]])

There is one more thing as boolean indexing

In [7]:
arr = np.array([5,10,20,30,40])
print(arr > 12)
print(arr[arr > 12])

[False False  True  True  True]
[20 30 40]


Reshaping the Array
you can also reshape the array as you like but be accurate about the dimesions

In [8]:
a = np.arange(1,31).reshape(5,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

Flattening of an array
you can covert the 2d array to 1d using the flatting function.

In [9]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])