arange - , linspace ,eye , rand , randint , randn

In [9]:
import numpy as np

In [10]:
#Q1.  1 se 100 tak numbers banao (arange)
arr = np.arange(1, 100)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [ ]:
# 1 to 100 tak numbers banao phir us number ka mean, max, min or sum nikalo.
arr = np.arange(1,100)
print("Mean",np.mean(arr))
print("Max",np.max(arr))
print("Min",np.min(arr))
print("Sum",np.sum(arr))

Mean 50.0
Max 99
Min 1
Sum 4950


In [11]:
# Q2. 0 se 1 kai each 50 equal space banwo(linspace)
arr = np.linspace(0,1,50)
print(arr)


[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


In [12]:
#Dono ka:
#Mean
#Max
#Min
#Sum nikaalo
arr = np.linspace(0,1,50)
print("Mean",np.mean(arr))
print("Max",np.max(arr))
print("Min",np.min(arr))
print("Sum",np.sum(arr))

Mean 0.5
Max 1.0
Min 0.0
Sum 25.0


In [14]:
# 5×5 identity matrix banao (eye)
arr = np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
# random
arr = np.random.rand(2,3)
print(arr)

[[0.36356739 0.24141004 0.03145862]
 [0.93938477 0.16714878 0.52943746]]


In [17]:
# A × I = A
# I × A = A
A = np.random.randint(1,10,(5,5))
I = np.eye(5,dtype=int)

print("Matrix A:\n",A)
print("\n Identity Matrix I: \n",I)

print("\nA * I =\n",A@I)
print("\nI * A = \n",I @ A)

Matrix A:
 [[7 7 5 3 2]
 [5 4 5 9 1]
 [5 5 5 2 1]
 [5 8 3 4 7]
 [2 9 9 1 8]]

 Identity Matrix I: 
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]

A * I =
 [[7 7 5 3 2]
 [5 4 5 9 1]
 [5 5 5 2 1]
 [5 8 3 4 7]
 [2 9 9 1 8]]

I * A = 
 [[7 7 5 3 2]
 [5 4 5 9 1]
 [5 5 5 2 1]
 [5 8 3 4 7]
 [2 9 9 1 8]]
