##Fancy Indexing
you can Pick elements from specific positions using a list/array of indices.

In [3]:
import numpy as np
arr = np.array([1,20,30,40,50])
arr[[0,2,4]]

array([ 1, 30, 50])

You can do this fancy indexing in 2D Matrix aswell

In [4]:
matrix = np.arange(1,13).reshape(3,4)
print(matrix)
matrix[[0,1,2],[1,2,3]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([ 2,  7, 12])

##Conditional Selection
Find values based on conditions or replace them.

In [5]:
arr = np.array([4,12,34,87,6])
arr[arr > 10]
np.where(arr>10)
np.where(arr>10,arr,0)

array([ 0, 12, 34, 87,  0])

##Sorting & Ordering
np.sort() → returns sorted array

np.argsort() → returns indices of sorted order

In [6]:
arr = np.array([4,12,34,87,6])
np.sort(arr)

array([ 4,  6, 12, 34, 87])

In [7]:
np.argsort(arr)

array([0, 4, 1, 2, 3])

##Concatenation & Stacking

In [8]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

Vertical & Horizontal Stacking

In [9]:
A = np.array([[1,2],[4,9]])
B = np.array([[5,6],[7,8]])

In [10]:
np.vstack([A,B])

array([[1, 2],
       [4, 9],
       [5, 6],
       [7, 8]])

In [11]:
np.hstack([B,A])

array([[5, 6, 1, 2],
       [7, 8, 4, 9]])