##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [2]:
import numpy as np
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

print(a+b)
print(a-b)
print(a*b)
print(a//b)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10 10 10 10]


These things are already different from List and if we talk about one more special power it is **Broadcasting**

In [3]:
a = np.array([1,2,3,4])
print(a * 2)

[2 4 6 8]


Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

In [4]:
arr = np.array([[1,2,3],[5,6,7]])
print(a * 5)

[ 5 10 15 20]


#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [5]:
arr = np.array([4,5,8,9,12,15,17,19])
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))

89
11.125
4
19
5.18260311040697
26.859375


You can also do the axis based operations row-Wise and Colum-wise

In [6]:
data = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [7]:
print(np.sum(data,axis=1)) # it is add row line of data.
print(np.sum(data,axis=0)) # it is add coloumn line of data.
print(np.mean(data,axis=0)) # it is a print medimum line(row) of data.
print(np.mean(data,axis=1)) # it is a print medimum line(coloumn) of data.

[ 6 15 24]
[12 15 18]
[4. 5. 6.]
[2. 5. 8.]
