# **Using NumPy**

Once you've installed NumPy you can import it as a library:

In [ ]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [ ]:
a = [1,2,3,4,5]
arr = np.array(a)
print(arr)

[1 2 3 4 5]


Lets create a matrix using list

In [ ]:
a = [[1,2,3],[4,5,6],[7,8,9]]
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Now lets see how matlix looks like using numpy arrays

In [ ]:
arr = np.array(a)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

there are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
np.zeros([3,4]) #row and columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.full(5,7)

array([7, 7, 7, 7, 7])

In [ ]:
np.full([5,5],7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [ ]:
arr = np.arange(0, 10, 2)   # start=0, stop=10, step=2
print(arr)

[0 2 4 6 8]


In [ ]:
arr = np.linspace(0, 1, 5)   # start=0, stop=1, 5 values
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
arr = np.eye(4)   # 4x4 identity matrix
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
arr = np.random.rand(2, 3)   # 2x3 array
print(arr)

[[0.57977045 0.04165422 0.45822095]
 [0.77345437 0.23146486 0.73424197]]


In [ ]:
arr = np.random.randint(1, 10, (3, 3))   # 3x3 integers from 1–9
print(arr)

[[2 9 7]
 [1 6 1]
 [3 7 6]]


In [ ]:
arr = np.random.randn(2, 4)   # 2x4 array
print(arr)

[[ 0.07347377  0.00554962 -1.47463013 -0.45858195]
 [-0.41830681  0.86342212  0.64891109 -0.83237775]]


arange → step-based values

linspace → fixed number of values

eye → identity matrix

rand → random floats (0–1)

randint → random integers in a range

randn → random values from bell curve distribution